apply plugin: 'com.android.application'

android {
    compileSdkVersion 35
    namespace("com.davemorrissey.labs.subscaleview.test")
    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 34
        applicationId "com.davemorrissey.labs.subscaleview.test"
    }

    sourceSets {
        main {
            assets.srcDirs = ['assets']
        }
    }
}

dependencies {
    implementation project(':library')
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
}
